version: '3'
services:
  c_prj:
    build:  
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: C_PROJECT
    volumes:
      - ./app/:/etc/app
      - ./app/simple-webserver/public/:/var/www/html/public
    ports:
      - "666:80"
    command: ["sh"]
    stdin_open: true
    tty: true
